### ISSUE TITLE
ST3 Package fails entirely with compilation error on initial installation.

### ISSUE THREAD

**Issue by robfrawley** [swdotcom/swdc-sublime#13]
**Describe the bug**
```paste below
After installing CodeTime on a brand-new installation of Windows and Sublime Text 3, the plugin fails compilation and errors out.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Install ST3
2. Install Package Control (using build-in installation command from ST3)
3. Install this package (the CodeTime package)
4. Open the console to see the compilation error.

**Expected behavior**
```paste below
I expect the package to not fail compilation and instead run.
```

**ACTUAL RESULTS**

```paste below
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin CodeTime.Software
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\robfr\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\Software.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\robfr\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\lib/SoftwareOffline.py", line 116
    if not timeData:
    ^
IndentationError: expected an indented block
reloading settings Packages/CodeTime/Software.sublime_settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (Version 1909 / Build 18363.720) [x64]
 - Plugin version: CodeTime 1.0.0 (Latest per https://packagecontrol.io/packages/CodeTime)

**Additional context**
```paste below

```

**Comment by joshuacheng** [comment]
The patch for this has been pushed to release now, thanks for pointing that out.
