### ISSUE TITLE
Package does not work (maybe just on Windows?)

### ISSUE THREAD

**Issue by Jackenmen** [swdotcom/swdc-sublime#45]
**Describe the bug**
I've been unable to log in at all.
The README says:
> Create an account to keep track of your coding data and unlock access to advanced data visualizations in the Code Time dashboard and web app. You can customize your profile, such as your work hours and office type, for advanced time tracking. You can also connect Outlook or Google Calendar to visualize your code time vs. meetings in a single calendar.
>
> Registering an account also lets you connect multiple code editors on multiple devices using the same email account. Your code time data will sync automatically across your devices.
>
> **Open Code Time by navigating to Tools > Code Time > Show Tree View. Click Sign up to create a new account, or click Log in to sign into an existing account.**

But the option "Tools > Code Time > Show Tree View" option does not do anything at all and I only get this traceback right after trying to use it:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "C:\Users\Jakub\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\lib/TreePanel.py", line 55, in run
  File "C:\Users\Jakub\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\lib/TreePanel.py", line 60, in showTree
  File "C:\Users\Jakub\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\lib/TreePanel.py", line 153, in create_tree
KeyError: 'averageDailyCodeTimeMinutes'
```

Also, I'm getting this traceback too, on plugin load:
```
Traceback (most recent call last):
  File "C:\Users\Jakub\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\lib/CommonUtil.py", line 48, in getHostname
    return socket.gethostname()
NameError: global name 'socket' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 528, in on_api_ready
    plc()
  File "C:\Users\Jakub\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\Software.py", line 447, in plugin_loaded
    initializeUser()
  File "C:\Users\Jakub\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\Software.py", line 464, in initializeUser
    result = createAnonymousUser()
  File "C:\Users\Jakub\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\lib/SoftwareHttp.py", line 143, in createAnonymousUser
    hostname = getHostname()
  File "C:\Users\Jakub\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\lib/CommonUtil.py", line 50, in getHostname
    return os.uname().nodename
AttributeError: 'module' object has no attribute 'uname'
```
And I get these in logs:
```
error POSTing to /user_encrypted_data for value: SOME HASH VALUE HERE
```

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
1. Install and load the package on Windows
2. See the logs (Ctrl+`)

**Expected behavior**
I was expecting to be able to log in and use the package.

**ACTUAL RESULTS**
I can't use the package per the description above;

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin version: CodeTime v2.5.7

**Additional context**
N/A

**Comment by xavluiz** [comment]
We apologize for the very late reply, but we've fixed issues around reading json data, along with a few other issues. The updates are in v2.6.1. Thank you.
